# tasks:
#   - init: |
#       mkdir -p ~/.npm-global
#       npm config set prefix ~/.npm-global
#       echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.bashrc
#       source ~/.bashrc
#       npm install -g @anthropic-ai/claude-code
#   - command: |
#       export PATH=~/.npm-global/bin:$PATH
#       echo "Workspace ready! Claude Code installed."

tasks:
  - init: |
      # 1) CLI がまだ無ければ 30 秒でインストール
      command -v claude >/dev/null || npm install -g @anthropic-ai/claude-code

      # 2) ブラウザでワンクリック認証（Device Flow）
      claude /login --device --yes

      echo "🎉 Claude Max 認証完了"


